services:

  keycloak-db:
    container_name: keycloak-db
    image: postgres:18
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-db:/var/lib/postgresql/

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./.config/dev/keycloak/conf:/opt/keycloak/conf
      - ./.config/dev/keycloak/imports:/opt/keycloak/data/import
    ports:
      - "10000:8080"
    depends_on:
      - keycloak-db

volumes:
  keycloak-db:
