services:

  houseshi-db:
    image: postgres:18
    container_name: houseshi-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: houseshi
    ports:
      - "5432:5432"
    volumes:
      - houseshi-db:/var/lib/postgresql/

  houseshi-core:
    build:
      context: ./api/backend
      dockerfile: ../../.config/dev/docker/python.Dockerfile
    container_name: houseshi_core
    environment:
      DATABASE_URL: postgres://postgres:password@houseshi-db:5432/houseshi
    ports:
      - "8000:8000"
    volumes:
      - ./api/backend:/app
    depends_on:
      - houseshi-db
    command: "uv run python manage.py runserver 0.0.0:8000"
    # command: "sleep infinity"

volumes:
  houseshi-db:
