db=postgres
db-username=postgres
db-password=password
db-name=keycloak
db-url=jdbc:postgresql://keycloak-db:5432/keycloak

# เปิดใช้งาน HTTP (ถ้าไม่ได้ใช้ HTTPS ในช่วงแรก)
http-enabled=true
hostname-strict=false