packages:
  - "client"
  - "component"

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild

supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - x64
    - arm64
